/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luc_fourestier_rbook_RoadBook */

#ifndef _Included_luc_fourestier_rbook_RoadBook
#define _Included_luc_fourestier_rbook_RoadBook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetBookName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetBookName
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetFilePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetFilePath
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetTitle
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _SetTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1SetTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetDescription
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _SetDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1SetDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetLocation
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _SetLocation
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1SetLocation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetImage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetImage
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _SetImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1SetImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetTotalDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetTotalDistance
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetPointCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1GetPointCount
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPoint
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetPreviousPoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1GetPreviousPoint
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetNextPoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1GetNextPoint
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetDistanceToNext
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetDistanceToNext
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetDistanceFromPrevious
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetDistanceFromPrevious
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointSpeech
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointSpeech
  (JNIEnv *, jobject, jint);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetNextPointSpeech
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetNextPointSpeech
  (JNIEnv *, jobject, jint);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _AddNewPointBefore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1AddNewPointBefore
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _AddNewPointAfter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadBook__1AddNewPointAfter
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _DeleteCurrentPoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1DeleteCurrentPoint
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Next
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Previous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Previous
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Reset
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _End
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1End
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
