/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luc_fourestier_rbook_BookManager */

#ifndef _Included_luc_fourestier_rbook_BookManager
#define _Included_luc_fourestier_rbook_BookManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _Create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_BookManager__1Create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _GetRoadBookListSerialized
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_BookManager__1GetRoadBookListSerialized
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _GetRoadBook
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_BookManager__1GetRoadBook
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _CreateRoadBook
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_BookManager__1CreateRoadBook
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _ImportRoadBook
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_BookManager__1ImportRoadBook
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _SaveRoadBook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_BookManager__1SaveRoadBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _ReleaseRoadBook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_BookManager__1ReleaseRoadBook
  (JNIEnv *, jobject, jint);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _DeleteRoadBook
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_BookManager__1DeleteRoadBook
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_BookManager
 * Method:    _Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_BookManager__1Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
