/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luc_fourestier_rbook_RoadBook */

#ifndef _Included_luc_fourestier_rbook_RoadBook
#define _Included_luc_fourestier_rbook_RoadBook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetBookName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetBookName
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetBookDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetBookDescription
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetBookLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetBookLocation
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetBookTotalDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetBookTotalDistance
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointName
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointObservation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointObservation
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointKilometer
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointKilometer
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointType
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointDirection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointDirection
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointDistanceToNext
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointDistanceToNext
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _GetCurrentPointDistanceFromPrevious
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadBook__1GetCurrentPointDistanceFromPrevious
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Next
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Next
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Previous
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Previous
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadBook
 * Method:    _Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadBook__1Reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
