/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luc_fourestier_rbook_RoadPoint */

#ifndef _Included_luc_fourestier_rbook_RoadPoint
#define _Included_luc_fourestier_rbook_RoadPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetDescription
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _SetDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadPoint__1SetDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetKilometer
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetKilometer
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _SetKilometer
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadPoint__1SetKilometer
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetType
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _SetType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadPoint__1SetType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetDirection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetDirection
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _SetDirection
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadPoint__1SetDirection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetImage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetImage
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _SetImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_RoadPoint__1SetImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     luc_fourestier_rbook_RoadPoint
 * Method:    _GetNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luc_fourestier_rbook_RoadPoint__1GetNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
