/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luc_fourestier_rbook_PictManager */

#ifndef _Included_luc_fourestier_rbook_PictManager
#define _Included_luc_fourestier_rbook_PictManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luc_fourestier_rbook_PictManager
 * Method:    _Populate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_luc_fourestier_rbook_PictManager__1Populate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     luc_fourestier_rbook_PictManager
 * Method:    _GetPictListSerialized
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_PictManager__1GetPictListSerialized
  (JNIEnv *, jobject);

/*
 * Class:     luc_fourestier_rbook_PictManager
 * Method:    _GetPict
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luc_fourestier_rbook_PictManager__1GetPict
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
